# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ivanova Ksenia
email: ivvlksenia@mail.ru
description: >- # this means to ignore newlines until "baseurl:"
 Student of Sarov National Research Nuclear University MEPhI 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username:
github_username: Ivvlksenia

[![|](http://raidho.by/wp-content/uploads/2017/04/vk.png)](https://ссылка) 
[![](https://im0-tub-ru.yandex.net/i?id=2568d09feffe96a8efe80608f35e17d9&n=13)](https://travis-ci.org/joemccann/dillinger)
[![](http://rubukkit.org/data/avatars/m/94/94042.jpg?1538728078)](https://github.com/Ivvlksenia/Ivvlksenia.github.io)

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
